name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: gcc 
      run: gcc -Wall -Werror -Wextra
    - name: Automatic pull request review
      uses: AndrewMusgrave/automatic-pull-request-review@0.0.2
    - name: Pull-Request-Typography
      uses: chyccs/pull-request-typography@master
      continue-on-error: true
      with:
        src_path: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Doc-label-check
      uses: fengtao1998/auto-labeling@v1.0
